name = "UnitsToValue"
uuid = "5caa0048-c25e-4a56-acb0-6c22dcda5114"
authors = ["Christian Hallas <hallaschristian@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
